#!/usr/bin/env python

import sys, re, socket

cache = dict()
fromStdin = False

def resolve(x):
    key = x.group(0)
    try:
        return "%s" % (cache[key])
    except KeyError:
        try:
            cache[key] = socket.gethostbyname(key)
        except:
            cache[key] = key

        if fromStdin:
            return "%s" % cache[key]
        else:
            return "%s\t%s" % (key, cache[key])

for f in [sys.stdin] or [open(x) for x in sys.argv[1:]] :
    if len(sys.argv) == 1:
        fromStdin = True

    for line in f:
        sys.stdout.write(re.sub("([0-9a-z][-\w]*[0-9a-z]\.)+[a-z][a-z0-9\-]{1,15}", resolve, line))

# End of file.
